version: "3"

services:

  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: "${DB_NAME}"
#      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    networks:
      - openlxp


  # sqlite3:
  #   # platform: linux/x86_64
  #   image: nouchka/sqlite3:latest
  #   ports:
  #     - '3306:3306'
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ./db/:/root/db/

  app:
    container_name: mmt-backend
    build:
      context: .
    ports:
      - "8000:8020"
    command: >
      sh -c ". /opt/app/start-app.sh"
    environment:
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DJANGO_SUPERUSER_USERNAME: "${DJANGO_SUPERUSER_USERNAME}"
      DJANGO_SUPERUSER_PASSWORD: "${DJANGO_SUPERUSER_PASSWORD}"
      DJANGO_SUPERUSER_EMAIL: "${DJANGO_SUPERUSER_EMAIL}"
      SECRET_KEY_VAL: "${SECRET_KEY_VAL}"
      LOG_PATH: "${LOG_PATH}"
      LOGIN_REDIRECT_URL: "${LOGIN_REDIRECT_URL}"
    volumes:
      - ./app:/opt/app/mmt-backend
    depends_on:
      - db
    networks:
      - openlxp

  redis:
    image: redis:alpine
    networks:
      - openlxp

  celery:
    build:
      context: .
    command: celery -A mmt_backend_project worker -l info --pool=solo
    volumes:
      - ./app:/opt/app/mmt-backend
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - app
    networks:
      - openlxp
    restart: on-failure

  celery-beat:
    build:
      context: .
    command: celery -A mmt_backend_project beat --scheduler django_celery_beat.schedulers:DatabaseScheduler --loglevel=info --pidfile=/tmp/celerybeat.pid
    volumes:
      - ./app:/opt/app/mmt-backend
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - app
    networks:
      - openlxp
    restart: on-failure
  
networks:
  openlxp:
    external: true